---
- hosts: servidors
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Actualitzar paquets 
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Instal·lar squid
      apt: name=squid update_cache=yes state=latest

    - name: Copiar fitxer configuració squid
      template:
        src: "files/squid.conf.j2"
        dest: "/etc/squid/squid.conf"

    - name: Copiar fitxer webs
      template:
        src: "files/denegado"
        dest: "/etc/squid/denegado"
      notify: Restart squid

    - name: Crear fitxer passwd
      file:
        path: "/etc/squid/passwd"
        state: touch 

    - name: Crear usuari1
      shell: htpasswd -mb /etc/squid/passwd {{ usuari1 }} {{ passwd_usuari1 }}

    - name: Crear usuari2
      shell: htpasswd -mb /etc/squid/passwd {{ usuari2 }} {{ passwd_usuari2 }} 
      notify: Restart squid

  handlers:
    - name: Restart squid
      service:
        name: squid
        state: restarted
